apiVersion: v1
kind: Secret
metadata:
  name: weather-api-secrets
  namespace: home-lab
type: Opaque
data:
  api-key: ${OPENWEATHER_API_KEY_BASE64}  # Will be replaced by script
---
apiVersion: v1
kind: Secret
metadata:
  name: smart-home-secrets
  namespace: home-lab
type: Opaque
data:
  token: ${HOME_ASSISTANT_TOKEN_BASE64}  # Will be replaced by script
---
apiVersion: v1
kind: Secret
metadata:
  name: media-server-secrets
  namespace: home-lab
type: Opaque
data:
  postgres-url: ${POSTGRES_URL_BASE64}  # Will be replaced by script
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: home-lab
type: Opaque
data:
  admin-password: ${GRAFANA_ADMIN_PASSWORD_BASE64}  # Will be replaced by script 